version: '3'
services:
  postgres:
    image: postgres:14.4
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 9b2b7565
      POSTGRES_DB: back
    ports:
      - '5432:5432'
    restart: always
